# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r
language: r
r:
  - oldrel
  - release
  - devel
  
sudo: false

cache: packages


addons:
  apt:
    packages:
      - valgrind
      
env:
  global:
    - VALGRIND_OPTS='--leak-check=full --track-origins=yes'
    - R_CHECK_ARGS: '--use-valgrind --as-cran'

  
dist: trusty

notifications:
  email:
    on_success: change
    on_failure: change

warnings_are_errors: true