---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, echo = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "README-"
)
```

# RcppGreedySetCover

A fast implementation of the greedy algorithm for the set cover problem using 'Rcpp'.

## Installation

Newest version from github: 

```{r gh-installation, eval = FALSE}
devtools::install_github("matthiaskaeding/RcppGreedySetCover")
```

CRAN:

```{r, eval = FALSE}
install.packages("RcppGreedySetCover")
```


## Example

This is a basic example which shows you how to use the main function:

```{r example}
# Create some data.
set.seed(333)
X <- data.table::rbindlist(
 lapply(
   seq_len(1e4L),
   function(x) list(element = sample.int(n = 1e3L, size = sample.int(50L, 1L)))
 ),
 idcol="set"
)

# Input is in long format.
head(X) 

# Run set cover
res <- RcppGreedySetCover::greedySetCover(X)

# Result is in long format.
head(res) 

# Check if all elements are covered:
setequal(res$element, X$element)
```
